AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Cache-clearing from Twitter and Facebook

Parameters:
  KinesisStream:
    Description: Name of the crier kinesis stream
    Type: String

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: socialCacheClearing-PROD
      Description: Clears content from Twitter and Facebook caches when content is updated
      Runtime: java8
      Handler: socialCacheClearing.Lambda::handler
      MemorySize: 1024
      Timeout: 15
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !Sub arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${KinesisStream}
            StartingPosition: LATEST
      CodeUri:
        Bucket: content-api-dist
        Key: content-api/PROD/social-cache-clearing/social-cache-clearing.jar
      Policies:
        - AWSLambdaBasicExecutionRole  # Managed Policy that includes CloudWatch log permissions
        - AWSLambdaKinesisExecutionRole
